import type { Metadata } from 'next'
import './globals.css'
import { quicksand } from '../utils/font'
import TanStackProvider from '@/utils/tanstackProvider'
import { AbsoluteContainer } from '@/components/molecule/absolute.component'
import Footer from '@/components/templates/footer.component'
import Header from '@/components/templates/header.component'

export const metadata: Metadata = {
    title: 'H&M | Online Fashion',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${quicksand.className} antialiased relative`}>
                <TanStackProvider>
                    <AbsoluteContainer />
                    <Header />
                    <main>{children}</main>
                    <Footer />
                </TanStackProvider>
            </body>
        </html>
    )
}
